FORMAT: 1A

# flyer
This api is a mockup api for flyer base advertisement service on mobile platform.

# Group Flyers
Flyers related resources of the **Flyers API**

## Flyers Collection [/flyers]
### List all Flyers [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Lotte Mart"
        }, {
          "id": 2, "title": "Pico Plaza"
        }]

### Create a Flyer [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Flyer [/flyers/{id}]
A single Flyer object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Flyer to perform action with. Has example value.

### Retrieve a Flyer [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Flyer [DELETE]
+ Response 204
